### ISSUE TITLE
Sample metrics that are exported by this exporter

### ISSUE THREAD

**Issue by yayajacky** [infinityworks/gar-exporter#4]
Hi, this looks very promising.
Could we get the metrics that will be output on a success run in the readme?

I can help generate one too if you don't have time,
thanks!

**Comment by iamrare** [comment]
currently it shows these:
```
ga_reporting_sessions{service_email="yourServiceAccount@projectName.iam.gserviceaccount.com",view_id="12345678"} 5349.0
# HELP ga_reporting_pageviews pageviews
# TYPE ga_reporting_pageviews gauge
ga_reporting_pageviews{service_email="yourServiceAccount@projectName.iam.gserviceaccount.com",view_id="12345678"} 19029.0
# HELP ga_reporting_users users
# TYPE ga_reporting_users gauge
ga_reporting_users{service_email="yourServiceAccount@projectName.iam.gserviceaccount.com",view_id="12345678"} 4174.0
```

I made few changes:
https://github.com/infinityworks/gar-exporter/pull/5

if it's merged, you can see some more:
https://github.com/iamrare/gar-exporter/pull/1#issuecomment-600029085

I will add in the README

**Comment by Rucknar** [comment]
Merged, thanks @iamrare

**Comment by iamrare** [comment]
Thank you!
